unit uLang;

{ =============================================================================
  وحدة النصوص متعددة اللغات  /  Unite des libelles multilingues

  اللغات المدعومة : العربية (الافتراضية) والفرنسية.
  Langues supportees : arabe (par defaut) et francais.

  كل النصوص متغيرات وليست ثوابت، حتى يمكن تبديل اللغة أثناء التشغيل.
  ملفات .dfm تبقى بمحارف ASCII فقط، والتسميات تُسند في FormCreate.

  لإضافة لغة ثالثة : أضف قيمة إلى TAppLang ثم إجراء LoadXxx مقابلا.
  ============================================================================= }

interface

type
  TAppLang = (langAR, langFR);

var
  R_AppTitle         : string;
  R_AppShort         : string;
  R_SchoolDefault    : string;
  R_PlaceDefault     : string;
  R_Ok               : string;
  R_Cancel           : string;
  R_Close            : string;
  R_Save             : string;
  R_New              : string;
  R_Edit             : string;
  R_Delete           : string;
  R_Search           : string;
  R_Refresh          : string;
  R_Print            : string;
  R_Export           : string;
  R_Yes              : string;
  R_No               : string;
  R_All              : string;
  R_None             : string;
  R_MsgConfirmDel    : string;
  R_MsgSaved         : string;
  R_MsgDeleted       : string;
  R_MsgNoRecord      : string;
  R_MsgRequired      : string;
  R_MsgErrTitle      : string;
  R_MsgInfoTitle     : string;
  R_MsgConfirmTitle  : string;
  R_LoginTitle       : string;
  R_LoginUser        : string;
  R_LoginPass        : string;
  R_LoginBtn         : string;
  R_LoginFailed      : string;
  R_LoginDisabled    : string;
  R_LoginWelcome     : string;
  R_MnuFile          : string;
  R_MnuData          : string;
  R_MnuAbsence       : string;
  R_MnuDocs          : string;
  R_MnuReports       : string;
  R_MnuTools         : string;
  R_MnuHelp          : string;
  R_MnuStudents      : string;
  R_MnuClasses       : string;
  R_MnuSubjects      : string;
  R_MnuSlots         : string;
  R_MnuYears         : string;
  R_MnuDailyAbs      : string;
  R_MnuJustify       : string;
  R_MnuLate          : string;
  R_MnuNotices       : string;
  R_MnuPermit        : string;
  R_MnuCertificate   : string;
  R_MnuDailyRep      : string;
  R_MnuAbsRegister   : string;
  R_MnuStats         : string;
  R_MnuUsers         : string;
  R_MnuSettings      : string;
  R_MnuBackup        : string;
  R_MnuRestore       : string;
  R_MnuLogout        : string;
  R_MnuExit          : string;
  R_MnuAbout         : string;
  R_StatUser         : string;
  R_StatDate         : string;
  R_StatDB           : string;
  R_StuTitle         : string;
  R_StuMatricule     : string;
  R_StuRegNo         : string;
  R_StuLastName      : string;
  R_StuFirstName     : string;
  R_StuGender        : string;
  R_StuMale          : string;
  R_StuFemale        : string;
  R_StuBirthDate     : string;
  R_StuBirthPlace    : string;
  R_StuClass         : string;
  R_StuRegime        : string;
  R_StuExtern        : string;
  R_StuSemiIntern    : string;
  R_StuIntern        : string;
  R_StuFather        : string;
  R_StuMother        : string;
  R_StuSocial        : string;
  R_StuSocNormal     : string;
  R_StuSocOrphan     : string;
  R_StuSocDivorced   : string;
  R_StuSocNeedy      : string;
  R_StuSiblings      : string;
  R_StuSibSchooled   : string;
  R_StuGuardian      : string;
  R_StuGuardPhone    : string;
  R_StuGuardEmail    : string;
  R_StuGuardAddr     : string;
  R_StuEnrollDate    : string;
  R_StuExitDate      : string;
  R_StuActive        : string;
  R_StuNotes         : string;
  R_StuSearchHint    : string;
  R_StuCount         : string;
  R_StuFileTab       : string;
  R_StuListTab       : string;
  R_StuAbsTab        : string;
  R_RefTitle         : string;
  R_RefLevels        : string;
  R_RefClasses       : string;
  R_RefSubjects      : string;
  R_RefTeachers      : string;
  R_RefSlots         : string;
  R_RefYears         : string;
  R_LevName          : string;
  R_LevOrder         : string;
  R_ClsName          : string;
  R_ClsLevel         : string;
  R_ClsYear          : string;
  R_ClsRoom          : string;
  R_ClsCapacity      : string;
  R_SubName          : string;
  R_SubCoef          : string;
  R_TchLastName      : string;
  R_TchFirstName     : string;
  R_TchPhone         : string;
  R_TchEmail         : string;
  R_TchSubject       : string;
  R_SltLabel         : string;
  R_SltPart          : string;
  R_SltMorning       : string;
  R_SltEvening       : string;
  R_SltStart         : string;
  R_SltEnd           : string;
  R_YrLabel          : string;
  R_YrStart          : string;
  R_YrEnd            : string;
  R_YrCurrent        : string;
  R_AbsTitle         : string;
  R_AbsDate          : string;
  R_AbsClass         : string;
  R_AbsSlot          : string;
  R_AbsSubject       : string;
  R_AbsTeacher       : string;
  R_AbsLoad          : string;
  R_AbsSaveAll       : string;
  R_AbsPresent       : string;
  R_AbsAbsent        : string;
  R_AbsLate          : string;
  R_AbsState         : string;
  R_AbsMinutes       : string;
  R_AbsJustified     : string;
  R_AbsReason        : string;
  R_AbsMarkAllPres   : string;
  R_AbsMarkAllAbs    : string;
  R_AbsSummary       : string;
  R_AbsNoClass       : string;
  R_AbsNoStudents    : string;
  R_AbsSavedFmt      : string;
  R_JusTitle         : string;
  R_JusFrom          : string;
  R_JusTo            : string;
  R_JusOnlyUnjust    : string;
  R_JusMarkJust      : string;
  R_JusMarkUnjust    : string;
  R_JusReasonAsk     : string;
  R_NotTitle         : string;
  R_NotKind          : string;
  R_NotFirst         : string;
  R_NotSecond        : string;
  R_NotRadiation     : string;
  R_NotSummon        : string;
  R_NotNo            : string;
  R_NotIssueDate     : string;
  R_NotMeetDate      : string;
  R_NotMeetTime      : string;
  R_NotTopic         : string;
  R_NotAbsCount      : string;
  R_NotDelivered     : string;
  R_NotGenerate      : string;
  R_NotPrintDoc      : string;
  R_NotGenDone       : string;
  R_NotGenNone       : string;
  R_PrmTitle         : string;
  R_PrmDate          : string;
  R_PrmTime          : string;
  R_PrmReason        : string;
  R_CrtTitle         : string;
  R_CrtNo            : string;
  R_CrtPurpose       : string;
  R_CrtCopies        : string;
  R_RepTitle         : string;
  R_RepDaily         : string;
  R_RepRegister      : string;
  R_RepByClass       : string;
  R_RepTopAbsent     : string;
  R_RepAttendRate    : string;
  R_RepPeriod        : string;
  R_RepGenerate      : string;
  R_RepNoData        : string;
  R_RepOpened        : string;
  R_UsrTitle         : string;
  R_UsrLogin         : string;
  R_UsrFullName      : string;
  R_UsrRole          : string;
  R_UsrRoleAdmin     : string;
  R_UsrRoleAdvisor   : string;
  R_UsrRoleSuperv    : string;
  R_UsrActive        : string;
  R_UsrNewPass       : string;
  R_UsrConfirmPass   : string;
  R_UsrPassMismatch  : string;
  R_UsrNoRights      : string;
  R_UsrLastAdmin     : string;
  R_SetTitle         : string;
  R_SetDirection     : string;
  R_SetSchool        : string;
  R_SetAddress       : string;
  R_SetPhone         : string;
  R_SetFax           : string;
  R_SetEmail         : string;
  R_SetDirector      : string;
  R_SetAdvisor       : string;
  R_SetThresholds    : string;
  R_SetThr1          : string;
  R_SetThr2          : string;
  R_SetThr3          : string;
  R_BakDone          : string;
  R_BakConfirmRest   : string;
  R_BakRestDone      : string;
  R_AboutText        : string;
  R_LoginDefHint     : string;
  R_LoginTooMany     : string;
  R_LangMenu         : string;
  R_LangArabic       : string;
  R_LangFrench       : string;
  R_DashTitle        : string;
  R_LblYear          : string;
  R_LblClass         : string;
  R_DashStudents     : string;
  R_DashClasses      : string;
  R_DashAbsToday     : string;
  R_DashUnjust       : string;
  R_BakFailed        : string;
  R_RestFailed       : string;
  R_StuDelHasAbs1    : string;
  R_StuDelHasAbs2    : string;
  R_StuDelHasAbs3    : string;
  R_RepStuList       : string;
  R_ColNum           : string;
  R_ColItem          : string;
  R_ColValue         : string;
  R_TotalPrefix      : string;
  R_SuffixStudents   : string;
  R_SuffixRecords    : string;
  R_SignAdvisor      : string;
  R_SignSupervisor   : string;
  R_SignDirector     : string;
  R_DirectorPrefix   : string;
  R_GuardianPrefix   : string;
  R_AtDate           : string;
  R_StuAbsSummaryFmt : string;
  R_YrSetCurrent     : string;
  R_ClsDelHasStu1    : string;
  R_AbsHint          : string;
  R_AbsPressLoad     : string;
  R_RepDailyAbs      : string;
  R_ColTime          : string;
  R_AbsDayTotal      : string;
  R_JusCount         : string;
  R_JusProcessed     : string;
  R_JusMedCert       : string;
  R_JusConfirmUnjust : string;
  R_FromLbl          : string;
  R_ToLbl            : string;
  R_UsrPassHint      : string;
  R_UsrCreatedAt     : string;
  R_UsrPassRequired  : string;
  R_UsrLoginTaken    : string;
  R_UsrNoSelfDelete  : string;
  R_SetThrHint       : string;
  R_SetThrOrder      : string;
  R_RepType          : string;
  R_RepRows          : string;
  R_RepPreview       : string;
  R_RepHintDaily     : string;
  R_RepHintReg       : string;
  R_RepHintClass     : string;
  R_RepHintTop       : string;
  R_RepHintRate      : string;
  R_ColTotal         : string;
  R_ColJust          : string;
  R_ColUnjust        : string;
  R_ColTotalAbs      : string;
  R_RepPrintOnly     : string;
  R_RepRowCount      : string;
  R_RepRateTitle     : string;
  R_RepWorkDays      : string;
  R_RepSlotsPerDay   : string;
  R_ColNbStudents    : string;
  R_ColPossible      : string;
  R_ColAbsHours      : string;
  R_ColRateAbs       : string;
  R_ColRatePres      : string;
  R_RepGlobalAbs     : string;
  R_RepGlobalPres    : string;
  R_NotStudent       : string;
  R_NotSelectStudent : string;
  R_NotSender        : string;
  R_NotRecipient     : string;
  R_NotAddress       : string;
  R_NotStudentName   : string;
  R_PrmDefReason     : string;
  R_PrmDocTitle      : string;
  R_CrtDefPurpose    : string;
  R_CrtDocTitle      : string;
  R_CrtNoPrefix      : string;
  R_RepHdrRepublic   : string;
  R_RepHdrMinistry   : string;

  R_SetMediaGroup   : string;
  R_SetLogo         : string;
  R_SetCover        : string;
  R_SetPickImg      : string;
  R_SetClearImg     : string;
  R_SetImgHint      : string;
  R_CardSubStudents : string;
  R_CardSubAbsence  : string;
  R_CardSubJustify  : string;
  R_CardSubNotices  : string;
  R_CardSubDocs     : string;
  R_CardSubReports  : string;
  R_CardSubRefData  : string;
  R_CardSubUsers    : string;
  R_CardSubSettings : string;

  R_MnuSampleData                  : string;
  R_SampleConfirm                  : string;
  R_SampleDone                     : string;
  R_SampleNone                     : string;

{ --- تسيير اللغة / Gestion de la langue --------------------------------- }
procedure SetLanguage(ALang: TAppLang);
procedure SetLanguageByCode(const ACode: string);
function  CurrentLang: TAppLang;
function  LangCode: string;
function  IsRTL: Boolean;
function  LangDisplayName(ALang: TAppLang): string;

implementation

uses SysUtils;

var
  FLang : TAppLang = langAR;

{ ==========================================================================
  العربية / Arabe
  ========================================================================== }
procedure LoadArabic;
begin
  R_AppTitle         := 'برنامج متابعة الغيابات اليومية للتلاميذ';
  R_AppShort         := 'تسيير الغيابات';
  R_SchoolDefault    := 'متوسطة الشهيد بالعربي أحمد';
  R_PlaceDefault     := 'سيدي طيفور - البيض';
  R_Ok               := 'موافق';
  R_Cancel           := 'إلغاء';
  R_Close            := 'إغلاق';
  R_Save             := 'حفظ';
  R_New              := 'جديد';
  R_Edit             := 'تعديل';
  R_Delete           := 'حذف';
  R_Search           := 'بحث';
  R_Refresh          := 'تحديث';
  R_Print            := 'طباعة';
  R_Export           := 'تصدير';
  R_Yes              := 'نعم';
  R_No               := 'لا';
  R_All              := '- الكل -';
  R_None             := '- بدون -';
  R_MsgConfirmDel    := 'هل تريد فعلا حذف السجل المحدد ؟';
  R_MsgSaved         := 'تم حفظ البيانات بنجاح.';
  R_MsgDeleted       := 'تم حذف السجل بنجاح.';
  R_MsgNoRecord      := 'لا يوجد سجل محدد.';
  R_MsgRequired      := 'يرجى ملء الحقول الإجبارية.';
  R_MsgErrTitle      := 'خطأ';
  R_MsgInfoTitle     := 'إعلام';
  R_MsgConfirmTitle  := 'تأكيد';
  R_LoginTitle       := 'تسجيل الدخول';
  R_LoginUser        := 'اسم المستخدم :';
  R_LoginPass        := 'كلمة المرور :';
  R_LoginBtn         := 'دخول';
  R_LoginFailed      := 'اسم المستخدم أو كلمة المرور غير صحيحة.';
  R_LoginDisabled    := 'هذا الحساب موقوف. اتصل بمسؤول النظام.';
  R_LoginWelcome     := 'مرحبا بك : ';
  R_MnuFile          := 'ملف';
  R_MnuData          := 'البيانات الأساسية';
  R_MnuAbsence       := 'الغيابات';
  R_MnuDocs          := 'الوثائق';
  R_MnuReports       := 'التقارير والإحصائيات';
  R_MnuTools         := 'أدوات';
  R_MnuHelp          := 'مساعدة';
  R_MnuStudents      := 'التلاميذ';
  R_MnuClasses       := 'الأقسام والمستويات';
  R_MnuSubjects      := 'المواد والأساتذة';
  R_MnuSlots         := 'الحصص والتوقيت';
  R_MnuYears         := 'السنوات الدراسية';
  R_MnuDailyAbs      := 'تسجيل الغيابات اليومية';
  R_MnuJustify       := 'تبرير الغيابات';
  R_MnuLate          := 'التأخرات';
  R_MnuNotices       := 'الإشعارات والاستدعاءات';
  R_MnuPermit        := 'ورقة الدخول';
  R_MnuCertificate   := 'الشهادة المدرسية';
  R_MnuDailyRep      := 'التقرير اليومي';
  R_MnuAbsRegister   := 'سجل الغيابات والتأخرات';
  R_MnuStats         := 'إحصائيات ونسب الحضور';
  R_MnuUsers         := 'المستخدمون';
  R_MnuSettings      := 'إعدادات المؤسسة';
  R_MnuBackup        := 'نسخة احتياطية لقاعدة البيانات';
  R_MnuRestore       := 'استرجاع نسخة احتياطية';
  R_MnuLogout        := 'تغيير المستخدم';
  R_MnuExit          := 'خروج';
  R_MnuAbout         := 'حول البرنامج';
  R_StatUser         := 'المستخدم : ';
  R_StatDate         := 'التاريخ : ';
  R_StatDB           := 'قاعدة البيانات : ';
  R_StuTitle         := 'تسيير ملفات التلاميذ';
  R_StuMatricule     := 'رقم التعريف المدرسي';
  R_StuRegNo         := 'رقم التسجيل';
  R_StuLastName      := 'اللقب';
  R_StuFirstName     := 'الاسم';
  R_StuGender        := 'الجنس';
  R_StuMale          := 'ذكر';
  R_StuFemale        := 'أنثى';
  R_StuBirthDate     := 'تاريخ الميلاد';
  R_StuBirthPlace    := 'مكان الميلاد';
  R_StuClass         := 'القسم';
  R_StuRegime        := 'الصفة';
  R_StuExtern        := 'خارجي';
  R_StuSemiIntern    := 'نصف داخلي';
  R_StuIntern        := 'داخلي';
  R_StuFather        := 'اسم الأب';
  R_StuMother        := 'اسم ولقب الأم';
  R_StuSocial        := 'الحالة الاجتماعية';
  R_StuSocNormal     := 'عادية';
  R_StuSocOrphan     := 'يتيم';
  R_StuSocDivorced   := 'مطلق الأبوين';
  R_StuSocNeedy      := 'معوز';
  R_StuSiblings      := 'عدد الإخوة';
  R_StuSibSchooled   := 'الإخوة المتمدرسون';
  R_StuGuardian      := 'الولي';
  R_StuGuardPhone    := 'هاتف الولي';
  R_StuGuardEmail    := 'البريد الإلكتروني';
  R_StuGuardAddr     := 'العنوان الشخصي للولي';
  R_StuEnrollDate    := 'تاريخ التسجيل';
  R_StuExitDate      := 'تاريخ الخروج';
  R_StuActive        := 'يزاول دراسته';
  R_StuNotes         := 'ملاحظات';
  R_StuSearchHint    := 'اكتب اللقب أو الاسم أو رقم التعريف ...';
  R_StuCount         := 'عدد التلاميذ : ';
  R_StuFileTab       := 'استمارة معلومات التلميذ';
  R_StuListTab       := 'قائمة التلاميذ';
  R_StuAbsTab        := 'غيابات التلميذ';
  R_RefTitle         := 'البيانات الأساسية';
  R_RefLevels        := 'المستويات';
  R_RefClasses       := 'الأقسام';
  R_RefSubjects      := 'المواد';
  R_RefTeachers      := 'الأساتذة';
  R_RefSlots         := 'الحصص';
  R_RefYears         := 'السنوات الدراسية';
  R_LevName          := 'تسمية المستوى';
  R_LevOrder         := 'الترتيب';
  R_ClsName          := 'تسمية القسم';
  R_ClsLevel         := 'المستوى';
  R_ClsYear          := 'السنة الدراسية';
  R_ClsRoom          := 'القاعة';
  R_ClsCapacity      := 'الطاقة الاستيعابية';
  R_SubName          := 'تسمية المادة';
  R_SubCoef          := 'المعامل';
  R_TchLastName      := 'اللقب';
  R_TchFirstName     := 'الاسم';
  R_TchPhone         := 'الهاتف';
  R_TchEmail         := 'البريد الإلكتروني';
  R_TchSubject       := 'المادة';
  R_SltLabel         := 'تسمية الحصة';
  R_SltPart          := 'الفترة';
  R_SltMorning       := 'صباحية';
  R_SltEvening       := 'مسائية';
  R_SltStart         := 'من الساعة';
  R_SltEnd           := 'إلى الساعة';
  R_YrLabel          := 'السنة الدراسية';
  R_YrStart          := 'تاريخ البداية';
  R_YrEnd            := 'تاريخ النهاية';
  R_YrCurrent        := 'السنة الجارية';
  R_AbsTitle         := 'تسجيل الغيابات اليومية';
  R_AbsDate          := 'التاريخ';
  R_AbsClass         := 'القسم';
  R_AbsSlot          := 'الحصة';
  R_AbsSubject       := 'المادة';
  R_AbsTeacher       := 'الأستاذ';
  R_AbsLoad          := 'عرض قائمة التلاميذ';
  R_AbsSaveAll       := 'حفظ كشف الغيابات';
  R_AbsPresent       := 'حاضر';
  R_AbsAbsent        := 'غائب';
  R_AbsLate          := 'متأخر';
  R_AbsState         := 'الحالة';
  R_AbsMinutes       := 'دقائق التأخر';
  R_AbsJustified     := 'مبرر';
  R_AbsReason        := 'سبب الغياب';
  R_AbsMarkAllPres   := 'تعليم الكل حاضر';
  R_AbsMarkAllAbs    := 'تعليم الكل غائب';
  R_AbsSummary       := 'الحاضرون : %d   الغائبون : %d   المتأخرون : %d';
  R_AbsNoClass       := 'يرجى اختيار القسم والحصة أولا.';
  R_AbsNoStudents    := 'لا يوجد تلاميذ مسجلون في هذا القسم.';
  R_AbsSavedFmt      := 'تم حفظ كشف الغيابات : %d عملية.';
  R_JusTitle         := 'تبرير الغيابات';
  R_JusFrom          := 'من تاريخ';
  R_JusTo            := 'إلى تاريخ';
  R_JusOnlyUnjust    := 'غير المبررة فقط';
  R_JusMarkJust      := 'تبرير المحدد';
  R_JusMarkUnjust    := 'إلغاء التبرير';
  R_JusReasonAsk     := 'أدخل سبب التبرير (شهادة طبية، سبب عائلي ...) :';
  R_NotTitle         := 'الإشعارات والاستدعاءات';
  R_NotKind          := 'نوع الوثيقة';
  R_NotFirst         := 'إشعار أول بالغياب';
  R_NotSecond        := 'إشعار ثان بالغياب';
  R_NotRadiation     := 'إعذار بالشطب';
  R_NotSummon        := 'استدعاء الولي';
  R_NotNo            := 'رقم الإرسال';
  R_NotIssueDate     := 'تاريخ التحرير';
  R_NotMeetDate      := 'تاريخ الحضور';
  R_NotMeetTime      := 'الساعة';
  R_NotTopic         := 'الموضوع';
  R_NotAbsCount      := 'عدد الغيابات';
  R_NotDelivered     := 'تم التبليغ';
  R_NotGenerate      := 'اقتراح الإشعارات آليا';
  R_NotPrintDoc      := 'طباعة الوثيقة';
  R_NotGenDone       := 'تم اقتراح %d إشعار حسب عتبات النظام الداخلي.';
  R_NotGenNone       := 'لا يوجد تلميذ بلغ عتبة الإشعار حاليا.';
  R_PrmTitle         := 'ورقة الدخول إلى القسم';
  R_PrmDate          := 'التاريخ';
  R_PrmTime          := 'على الساعة';
  R_PrmReason        := 'السبب';
  R_CrtTitle         := 'الشهادة المدرسية';
  R_CrtNo            := 'الرقم التسلسلي';
  R_CrtPurpose       := 'الغرض من الشهادة';
  R_CrtCopies        := 'عدد النسخ';
  R_RepTitle         := 'التقارير والإحصائيات';
  R_RepDaily         := 'التقرير اليومي للغيابات';
  R_RepRegister      := 'سجل الغيابات والتأخرات';
  R_RepByClass       := 'حوصلة حسب القسم';
  R_RepTopAbsent     := 'التلاميذ الأكثر غيابا';
  R_RepAttendRate    := 'نسبة الحضور والغياب';
  R_RepPeriod        := 'الفترة';
  R_RepGenerate      := 'إنشاء التقرير';
  R_RepNoData        := 'لا توجد معطيات مطابقة للمعايير المختارة.';
  R_RepOpened        := 'تم إنشاء التقرير وفتحه في المتصفح للطباعة.';
  R_UsrTitle         := 'تسيير المستخدمين';
  R_UsrLogin         := 'اسم المستخدم';
  R_UsrFullName      := 'الاسم الكامل';
  R_UsrRole          := 'الصلاحية';
  R_UsrRoleAdmin     := 'مسؤول النظام';
  R_UsrRoleAdvisor   := 'مستشار التربية';
  R_UsrRoleSuperv    := 'مشرف التربية';
  R_UsrActive        := 'نشط';
  R_UsrNewPass       := 'كلمة المرور الجديدة';
  R_UsrConfirmPass   := 'تأكيد كلمة المرور';
  R_UsrPassMismatch  := 'كلمتا المرور غير متطابقتين.';
  R_UsrNoRights      := 'ليست لديك الصلاحية للقيام بهذه العملية.';
  R_UsrLastAdmin     := 'لا يمكن حذف أو توقيف آخر حساب لمسؤول النظام.';
  R_SetTitle         := 'إعدادات المؤسسة';
  R_SetDirection     := 'مديرية التربية';
  R_SetSchool        := 'تسمية المؤسسة';
  R_SetAddress       := 'العنوان';
  R_SetPhone         := 'الهاتف';
  R_SetFax           := 'الفاكس';
  R_SetEmail         := 'البريد الإلكتروني';
  R_SetDirector      := 'مدير المؤسسة';
  R_SetAdvisor       := 'مستشار التربية';
  R_SetThresholds    := 'عتبات الإشعار (عدد الغيابات غير المبررة)';
  R_SetThr1          := 'الإشعار الأول';
  R_SetThr2          := 'الإشعار الثاني';
  R_SetThr3          := 'الإعذار بالشطب';
  R_BakDone          := 'تم إنشاء النسخة الاحتياطية في : ';
  R_BakConfirmRest   := 'سيتم استبدال قاعدة البيانات الحالية بالنسخة المختارة.' + #13#10 + 'هل تريد المتابعة ؟';
  R_BakRestDone      := 'تم استرجاع النسخة الاحتياطية. سيتم إغلاق البرنامج، أعد تشغيله.';
  R_AboutText        := 'برنامج متابعة الغيابات اليومية للتلاميذ' + #13#10 + #13#10 + 'مذكرة تخرج لنيل شهادة تقني سامي في الإعلام الآلي' + #13#10 + 'تخصص : قاعدة معطيات' + #13#10 + 'المعهد الوطني المتخصص في التكوين المهني - بن سعيدي عبد العاطي - البيض' + #13#10 + #13#10 + 'مؤسسة التربص : متوسطة الشهيد بالعربي أحمد - سيدي طيفور' + #13#10 + #13#10 + 'أدوات الإنجاز : Delphi (Object Pascal) + Microsoft Access' + #13#10 + 'منهجية التصميم : MERISE (MCD / MLD)';
  R_LoginDefHint     := 'الحساب الافتراضي : admin / admin';
  R_LoginTooMany     := 'تم تجاوز عدد المحاولات المسموح بها. سيتم إغلاق البرنامج.';
  R_LangMenu         := 'اللغة';
  R_LangArabic       := 'العربية';
  R_LangFrench       := 'الفرنسية';
  R_DashTitle        := 'حوصلة سريعة';
  R_LblYear          := 'السنة الدراسية : ';
  R_LblClass         := 'القسم : ';
  R_DashStudents     := 'عدد التلاميذ المزاولين : ';
  R_DashClasses      := 'عدد الأقسام : ';
  R_DashAbsToday     := 'غيابات اليوم : ';
  R_DashUnjust       := 'غيابات غير مبررة (المجموع) : ';
  R_BakFailed        := 'تعذر إنشاء النسخة الاحتياطية.';
  R_RestFailed       := 'تعذر استرجاع النسخة الاحتياطية.';
  R_StuDelHasAbs1    := 'هذا التلميذ مسجل عليه ';
  R_StuDelHasAbs2    := ' غياب / تأخر.';
  R_StuDelHasAbs3    := 'سيتم حذف كل هذه السجلات كذلك. هل تريد المتابعة ؟';
  R_RepStuList       := 'قائمة التلاميذ';
  R_ColNum           := 'الرقم';
  R_ColItem          := 'البيان';
  R_ColValue         := 'القيمة';
  R_TotalPrefix      := 'المجموع : ';
  R_SuffixStudents   := ' تلميذ.';
  R_SuffixRecords    := ' سجل.';
  R_SignAdvisor      := 'مستشار التربية : ';
  R_SignSupervisor   := 'مشرف التربية';
  R_SignDirector     := 'مدير المؤسسة';
  R_DirectorPrefix   := 'مدير المؤسسة : ';
  R_GuardianPrefix   := 'ولي التلميذ : ';
  R_AtDate           := ' في : ';
  R_StuAbsSummaryFmt := 'مجموع الغيابات : %d   منها غير مبررة : %d   -   مجموع التأخرات : %d';
  R_YrSetCurrent     := 'تعيين كسنة جارية';
  R_ClsDelHasStu1    := 'لا يمكن حذف هذا القسم : يوجد به ';
  R_AbsHint          := 'انقر على خانة "الحالة" أو "مبرر" لتغيير القيمة.';
  R_AbsPressLoad     := 'اضغط على زر عرض قائمة التلاميذ.';
  R_RepDailyAbs      := 'التقرير اليومي لغيابات التلاميذ';
  R_ColTime          := 'التوقيت';
  R_AbsDayTotal      := 'مجموع الحالات المسجلة في هذا اليوم : ';
  R_JusCount         := 'عدد السجلات : ';
  R_JusProcessed     := 'تمت معالجة ';
  R_JusMedCert       := 'شهادة طبية';
  R_JusConfirmUnjust := 'هل تريد إلغاء تبرير السجلات المحددة ؟';
  R_FromLbl          := 'من ';
  R_ToLbl            := ' إلى ';
  R_UsrPassHint      := 'اترك خانتي كلمة المرور فارغتين للإبقاء على الكلمة الحالية.';
  R_UsrCreatedAt     := 'تاريخ الإنشاء';
  R_UsrPassRequired  := 'يجب تحديد كلمة مرور للمستخدم الجديد.';
  R_UsrLoginTaken    := 'اسم المستخدم مستعمل من قبل.';
  R_UsrNoSelfDelete  := 'لا يمكنك حذف حسابك الخاص أثناء استعماله.';
  R_SetThrHint       := 'عدد الغيابات غير المبررة التي يقترح عندها البرنامج تحرير الوثيقة.';
  R_SetThrOrder      := 'يجب أن تكون العتبات متزايدة : العتبة 1 < العتبة 2 < العتبة 3.';
  R_RepType          := 'نوع التقرير';
  R_RepRows          := 'عدد الأسطر';
  R_RepPreview       := 'عرض';
  R_RepHintDaily     := 'كشف كل الغيابات والتأخرات المسجلة في يوم محدد.';
  R_RepHintReg       := 'سجل مفصل للغيابات والتأخرات خلال فترة.';
  R_RepHintClass     := 'حوصلة عدد الغيابات والتأخرات حسب كل قسم.';
  R_RepHintTop       := 'ترتيب التلاميذ حسب عدد الغيابات.';
  R_RepHintRate      := 'نسبة الحضور = 100% ناقص (الغيابات / (عدد التلاميذ × أيام العمل × عدد الحصص)).';
  R_ColTotal         := 'المجموع';
  R_ColJust          := 'مبررة';
  R_ColUnjust        := 'غير مبررة';
  R_ColTotalAbs      := 'مجموع الغيابات';
  R_RepPrintOnly     := 'هذا التقرير يُنشأ مباشرة للطباعة. اضغط على زر الطباعة.';
  R_RepRowCount      := 'عدد الأسطر : ';
  R_RepRateTitle     := 'نسبة الحضور والغياب حسب الأقسام';
  R_RepWorkDays      := '   -   أيام العمل : ';
  R_RepSlotsPerDay   := '   -   عدد الحصص في اليوم : ';
  R_ColNbStudents    := 'عدد التلاميذ';
  R_ColPossible      := 'الحصص الممكنة';
  R_ColAbsHours      := 'ساعات الغياب';
  R_ColRateAbs       := 'نسبة الغياب %';
  R_ColRatePres      := 'نسبة الحضور %';
  R_RepGlobalAbs     := 'النسبة العامة للغياب على مستوى المؤسسة : ';
  R_RepGlobalPres    := '   -   النسبة العامة للحضور : ';
  R_NotStudent       := 'التلميذ';
  R_NotSelectStudent := 'يرجى اختيار التلميذ.';
  R_NotSender        := 'المرسل';
  R_NotRecipient     := 'المرسل إليه';
  R_NotAddress       := 'العنوان';
  R_NotStudentName   := 'اسم ولقب التلميذ';
  R_PrmDefReason     := 'تأخر عن الدخول';
  R_PrmDocTitle      := 'رخصة الدخول إلى القسم';
  R_CrtDefPurpose    := 'للاستعمال فيما يخدم مصلحة المعني';
  R_CrtDocTitle      := 'شهـــادة مدرسيــة';
  R_CrtNoPrefix      := 'الرقم : ';
  R_RepHdrRepublic   := 'الجمهورية الجزائرية الديمقراطية الشعبية';
  R_RepHdrMinistry   := 'وزارة التربية الوطنية';
  R_SetMediaGroup   := 'شعار وصورة المؤسسة';
  R_SetLogo         := 'الشعار';
  R_SetCover        := 'صورة الواجهة';
  R_SetPickImg      := 'اختيار صورة ...';
  R_SetClearImg     := 'إزالة';
  R_SetImgHint      := 'الصيغ المقبولة : PNG أو JPG أو BMP. تُنسخ الصورة إلى مجلد البرنامج.';
  R_CardSubStudents := 'ملفات التلاميذ والتسجيلات';
  R_CardSubAbsence  := 'كشف الحضور والغياب اليومي';
  R_CardSubJustify  := 'معالجة الغيابات غير المبررة';
  R_CardSubNotices  := 'إشعارات واستدعاءات الأولياء';
  R_CardSubDocs     := 'ورقة الدخول والشهادة المدرسية';
  R_CardSubReports  := 'حوصلات ونسب الحضور';
  R_CardSubRefData  := 'المستويات والمواد والحصص';
  R_CardSubUsers    := 'الحسابات والصلاحيات';
  R_CardSubSettings := 'بيانات المؤسسة والعتبات';
  R_MnuSampleData                  := 'إدراج بيانات تجريبية';
  R_SampleConfirm                  := 'سيتم إدراج بيانات تجريبية كاملة : 90 تلميذا (ناجحو شهادة' +
                                      ' التعليم المتوسط 2026)، أساتذة، مستخدمون،' + #13#10 +
                                      'غيابات وتأخرات وتبريرات، إشعارات، أوراق دخول وشهادات مدرسية.' +
                                      #13#10 + #13#10 +
                                      'الجداول التي تحتوي على بيانات لن تُمس. هل تريد المتابعة ؟';
  R_SampleDone                     := 'تم إدراج البيانات التجريبية :';
  R_SampleNone                     := 'كل الجداول تحتوي على بيانات، لم يُضف أي سجل.';
end;

{ ==========================================================================
  الفرنسية / Francais
  ========================================================================== }
procedure LoadFrench;
begin
  R_AppTitle         := 'Suivi des absences journalières des élèves';
  R_AppShort         := 'Gestion des absences';
  R_SchoolDefault    := 'CEM Chahid Belarbi Ahmed';
  R_PlaceDefault     := 'Sidi Tifour - El Bayadh';
  R_Ok               := 'OK';
  R_Cancel           := 'Annuler';
  R_Close            := 'Fermer';
  R_Save             := 'Enregistrer';
  R_New              := 'Nouveau';
  R_Edit             := 'Modifier';
  R_Delete           := 'Supprimer';
  R_Search           := 'Rechercher';
  R_Refresh          := 'Actualiser';
  R_Print            := 'Imprimer';
  R_Export           := 'Exporter';
  R_Yes              := 'Oui';
  R_No               := 'Non';
  R_All              := '- Tous -';
  R_None             := '- Aucun -';
  R_MsgConfirmDel    := 'Voulez-vous vraiment supprimer l''enregistrement sélectionné ?';
  R_MsgSaved         := 'Les données ont été enregistrées avec succès.';
  R_MsgDeleted       := 'L''enregistrement a été supprimé.';
  R_MsgNoRecord      := 'Aucun enregistrement sélectionné.';
  R_MsgRequired      := 'Veuillez remplir les champs obligatoires.';
  R_MsgErrTitle      := 'Erreur';
  R_MsgInfoTitle     := 'Information';
  R_MsgConfirmTitle  := 'Confirmation';
  R_LoginTitle       := 'Authentification';
  R_LoginUser        := 'Nom d''utilisateur :';
  R_LoginPass        := 'Mot de passe :';
  R_LoginBtn         := 'Connexion';
  R_LoginFailed      := 'Nom d''utilisateur ou mot de passe incorrect.';
  R_LoginDisabled    := 'Ce compte est désactivé. Contactez l''administrateur.';
  R_LoginWelcome     := 'Bienvenue : ';
  R_MnuFile          := 'Fichier';
  R_MnuData          := 'Données de base';
  R_MnuAbsence       := 'Absences';
  R_MnuDocs          := 'Documents';
  R_MnuReports       := 'États et statistiques';
  R_MnuTools         := 'Outils';
  R_MnuHelp          := 'Aide';
  R_MnuStudents      := 'Élèves';
  R_MnuClasses       := 'Classes et niveaux';
  R_MnuSubjects      := 'Matières et enseignants';
  R_MnuSlots         := 'Séances et horaires';
  R_MnuYears         := 'Années scolaires';
  R_MnuDailyAbs      := 'Saisie des absences du jour';
  R_MnuJustify       := 'Justification des absences';
  R_MnuLate          := 'Retards';
  R_MnuNotices       := 'Avis et convocations';
  R_MnuPermit        := 'Billet d''entrée';
  R_MnuCertificate   := 'Certificat de scolarité';
  R_MnuDailyRep      := 'Rapport journalier';
  R_MnuAbsRegister   := 'Registre des absences et retards';
  R_MnuStats         := 'Statistiques et taux de présence';
  R_MnuUsers         := 'Utilisateurs';
  R_MnuSettings      := 'Paramètres de l''établissement';
  R_MnuBackup        := 'Sauvegarde de la base de données';
  R_MnuRestore       := 'Restaurer une sauvegarde';
  R_MnuLogout        := 'Changer d''utilisateur';
  R_MnuExit          := 'Quitter';
  R_MnuAbout         := 'À propos';
  R_StatUser         := 'Utilisateur : ';
  R_StatDate         := 'Date : ';
  R_StatDB           := 'Base : ';
  R_StuTitle         := 'Gestion des dossiers élèves';
  R_StuMatricule     := 'Matricule scolaire';
  R_StuRegNo         := 'N° d''inscription';
  R_StuLastName      := 'Nom';
  R_StuFirstName     := 'Prénom';
  R_StuGender        := 'Sexe';
  R_StuMale          := 'Masculin';
  R_StuFemale        := 'Féminin';
  R_StuBirthDate     := 'Date de naissance';
  R_StuBirthPlace    := 'Lieu de naissance';
  R_StuClass         := 'Classe';
  R_StuRegime        := 'Régime';
  R_StuExtern        := 'Externe';
  R_StuSemiIntern    := 'Demi-pensionnaire';
  R_StuIntern        := 'Interne';
  R_StuFather        := 'Nom du père';
  R_StuMother        := 'Nom et prénom de la mère';
  R_StuSocial        := 'Situation sociale';
  R_StuSocNormal     := 'Normale';
  R_StuSocOrphan     := 'Orphelin';
  R_StuSocDivorced   := 'Parents divorcés';
  R_StuSocNeedy      := 'Nécessiteux';
  R_StuSiblings      := 'Nombre de frères et sœurs';
  R_StuSibSchooled   := 'Frères et sœurs scolarisés';
  R_StuGuardian      := 'Tuteur';
  R_StuGuardPhone    := 'Téléphone du tuteur';
  R_StuGuardEmail    := 'Adresse e-mail';
  R_StuGuardAddr     := 'Adresse personnelle du tuteur';
  R_StuEnrollDate    := 'Date d''inscription';
  R_StuExitDate      := 'Date de sortie';
  R_StuActive        := 'Scolarisé';
  R_StuNotes         := 'Observations';
  R_StuSearchHint    := 'Tapez le nom, le prénom ou le matricule ...';
  R_StuCount         := 'Nombre d''élèves : ';
  R_StuFileTab       := 'Fiche de renseignements de l''élève';
  R_StuListTab       := 'Liste des élèves';
  R_StuAbsTab        := 'Absences de l''élève';
  R_RefTitle         := 'Données de base';
  R_RefLevels        := 'Niveaux';
  R_RefClasses       := 'Classes';
  R_RefSubjects      := 'Matières';
  R_RefTeachers      := 'Enseignants';
  R_RefSlots         := 'Séances';
  R_RefYears         := 'Années scolaires';
  R_LevName          := 'Désignation du niveau';
  R_LevOrder         := 'Ordre';
  R_ClsName          := 'Désignation de la classe';
  R_ClsLevel         := 'Niveau';
  R_ClsYear          := 'Année scolaire';
  R_ClsRoom          := 'Salle';
  R_ClsCapacity      := 'Capacité d''accueil';
  R_SubName          := 'Désignation de la matière';
  R_SubCoef          := 'Coefficient';
  R_TchLastName      := 'Nom';
  R_TchFirstName     := 'Prénom';
  R_TchPhone         := 'Téléphone';
  R_TchEmail         := 'Adresse e-mail';
  R_TchSubject       := 'Matière';
  R_SltLabel         := 'Désignation de la séance';
  R_SltPart          := 'Période';
  R_SltMorning       := 'Matin';
  R_SltEvening       := 'Après-midi';
  R_SltStart         := 'De';
  R_SltEnd           := 'À';
  R_YrLabel          := 'Année scolaire';
  R_YrStart          := 'Date de début';
  R_YrEnd            := 'Date de fin';
  R_YrCurrent        := 'Année courante';
  R_AbsTitle         := 'Saisie des absences journalières';
  R_AbsDate          := 'Date';
  R_AbsClass         := 'Classe';
  R_AbsSlot          := 'Séance';
  R_AbsSubject       := 'Matière';
  R_AbsTeacher       := 'Enseignant';
  R_AbsLoad          := 'Afficher la liste des élèves';
  R_AbsSaveAll       := 'Enregistrer la feuille d''absences';
  R_AbsPresent       := 'Présent';
  R_AbsAbsent        := 'Absent';
  R_AbsLate          := 'En retard';
  R_AbsState         := 'État';
  R_AbsMinutes       := 'Minutes de retard';
  R_AbsJustified     := 'Justifié';
  R_AbsReason        := 'Motif de l''absence';
  R_AbsMarkAllPres   := 'Tous présents';
  R_AbsMarkAllAbs    := 'Tous absents';
  R_AbsSummary       := 'Présents : %d   Absents : %d   Retards : %d';
  R_AbsNoClass       := 'Veuillez d''abord choisir la classe et la séance.';
  R_AbsNoStudents    := 'Aucun élève inscrit dans cette classe.';
  R_AbsSavedFmt      := 'Feuille d''absences enregistrée : %d opération(s).';
  R_JusTitle         := 'Justification des absences';
  R_JusFrom          := 'Du';
  R_JusTo            := 'Au';
  R_JusOnlyUnjust    := 'Non justifiées uniquement';
  R_JusMarkJust      := 'Justifier la sélection';
  R_JusMarkUnjust    := 'Annuler la justification';
  R_JusReasonAsk     := 'Saisissez le motif (certificat médical, raison familiale ...) :';
  R_NotTitle         := 'Avis et convocations';
  R_NotKind          := 'Type de document';
  R_NotFirst         := 'Premier avis d''absence';
  R_NotSecond        := 'Second avis d''absence';
  R_NotRadiation     := 'Mise en demeure de radiation';
  R_NotSummon        := 'Convocation du tuteur';
  R_NotNo            := 'N° d''envoi';
  R_NotIssueDate     := 'Date d''établissement';
  R_NotMeetDate      := 'Date de présentation';
  R_NotMeetTime      := 'Heure';
  R_NotTopic         := 'Objet';
  R_NotAbsCount      := 'Nb d''absences';
  R_NotDelivered     := 'Notifié';
  R_NotGenerate      := 'Proposer automatiquement';
  R_NotPrintDoc      := 'Imprimer le document';
  R_NotGenDone       := '%d avis proposé(s) selon les seuils du règlement intérieur.';
  R_NotGenNone       := 'Aucun élève n''a atteint le seuil pour le moment.';
  R_PrmTitle         := 'Billet d''entrée en classe';
  R_PrmDate          := 'Date';
  R_PrmTime          := 'À';
  R_PrmReason        := 'Motif';
  R_CrtTitle         := 'Certificat de scolarité';
  R_CrtNo            := 'N° d''ordre';
  R_CrtPurpose       := 'Objet du certificat';
  R_CrtCopies        := 'Nombre de copies';
  R_RepTitle         := 'États et statistiques';
  R_RepDaily         := 'Rapport journalier des absences';
  R_RepRegister      := 'Registre des absences et retards';
  R_RepByClass       := 'Synthèse par classe';
  R_RepTopAbsent     := 'Élèves les plus absents';
  R_RepAttendRate    := 'Taux de présence et d''absence';
  R_RepPeriod        := 'Période';
  R_RepGenerate      := 'Générer l''état';
  R_RepNoData        := 'Aucune donnée ne correspond aux critères choisis.';
  R_RepOpened        := 'L''état a été généré et ouvert dans le navigateur pour impression.';
  R_UsrTitle         := 'Gestion des utilisateurs';
  R_UsrLogin         := 'Nom d''utilisateur';
  R_UsrFullName      := 'Nom complet';
  R_UsrRole          := 'Profil';
  R_UsrRoleAdmin     := 'Administrateur';
  R_UsrRoleAdvisor   := 'Conseiller d''éducation';
  R_UsrRoleSuperv    := 'Surveillant';
  R_UsrActive        := 'Actif';
  R_UsrNewPass       := 'Nouveau mot de passe';
  R_UsrConfirmPass   := 'Confirmer le mot de passe';
  R_UsrPassMismatch  := 'Les deux mots de passe ne correspondent pas.';
  R_UsrNoRights      := 'Vous n''avez pas les droits nécessaires pour cette opération.';
  R_UsrLastAdmin     := 'Impossible de supprimer ou désactiver le dernier compte administrateur.';
  R_SetTitle         := 'Paramètres de l''établissement';
  R_SetDirection     := 'Direction de l''éducation';
  R_SetSchool        := 'Nom de l''établissement';
  R_SetAddress       := 'Adresse';
  R_SetPhone         := 'Téléphone';
  R_SetFax           := 'Fax';
  R_SetEmail         := 'Adresse e-mail';
  R_SetDirector      := 'Directeur de l''établissement';
  R_SetAdvisor       := 'Conseiller d''éducation';
  R_SetThresholds    := 'Seuils de déclenchement des avis (absences non justifiées)';
  R_SetThr1          := 'Premier avis';
  R_SetThr2          := 'Second avis';
  R_SetThr3          := 'Mise en demeure';
  R_BakDone          := 'Sauvegarde créée dans : ';
  R_BakConfirmRest   := 'La base de donnees actuelle sera remplacee par la sauvegarde choisie.' + #13#10 +
                      'Voulez-vous continuer ?';
  R_BakRestDone      := 'Sauvegarde restaurée. L''application va se fermer, relancez-la.';
  R_AboutText        := 'Suivi des absences journalieres des eleves' + #13#10 + #13#10 +
    'Memoire de fin de formation - Technicien Superieur en Informatique' + #13#10 +
    'Specialite : Base de donnees' + #13#10 +
    'INSFP Ben Saidi Abdelati - El Bayadh' + #13#10 + #13#10 +
    'Etablissement d''accueil : CEM Chahid Belarbi Ahmed - Sidi Tifour' + #13#10 + #13#10 +
    'Outils : Delphi (Object Pascal) + Microsoft Access' + #13#10 +
    'Methode de conception : MERISE (MCD / MLD)';
  R_LoginDefHint     := 'Compte par défaut : admin / admin';
  R_LoginTooMany     := 'Nombre de tentatives dépassé. L''application va se fermer.';
  R_LangMenu         := 'Langue';
  R_LangArabic       := 'Arabe';
  R_LangFrench       := 'Français';
  R_DashTitle        := 'Aperçu rapide';
  R_LblYear          := 'Année scolaire : ';
  R_LblClass         := 'Classe : ';
  R_DashStudents     := 'Élèves scolarisés : ';
  R_DashClasses      := 'Nombre de classes : ';
  R_DashAbsToday     := 'Absences du jour : ';
  R_DashUnjust       := 'Absences non justifiées (total) : ';
  R_BakFailed        := 'Échec de la création de la sauvegarde.';
  R_RestFailed       := 'Échec de la restauration de la sauvegarde.';
  R_StuDelHasAbs1    := 'Cet élève totalise ';
  R_StuDelHasAbs2    := ' absence(s) / retard(s).';
  R_StuDelHasAbs3    := 'Tous ces enregistrements seront également supprimés. Continuer ?';
  R_RepStuList       := 'Liste des élèves';
  R_ColNum           := 'N°';
  R_ColItem          := 'Désignation';
  R_ColValue         := 'Valeur';
  R_TotalPrefix      := 'Total : ';
  R_SuffixStudents   := ' élève(s).';
  R_SuffixRecords    := ' enregistrement(s).';
  R_SignAdvisor      := 'Conseiller d''éducation : ';
  R_SignSupervisor   := 'Le Surveillant';
  R_SignDirector     := 'Le Directeur';
  R_DirectorPrefix   := 'Le Directeur : ';
  R_GuardianPrefix   := 'Tuteur de l''élève : ';
  R_AtDate           := ', le : ';
  R_StuAbsSummaryFmt := 'Total absences : %d   dont non justifiées : %d   -   Total retards : %d';
  R_YrSetCurrent     := 'Définir comme année courante';
  R_ClsDelHasStu1    := 'Suppression impossible : cette classe contient ';
  R_AbsHint          := 'Cliquez sur la cellule « État » ou « Justifié » pour changer la valeur.';
  R_AbsPressLoad     := 'Cliquez sur « Afficher la liste des élèves ».';
  R_RepDailyAbs      := 'Rapport journalier des absences des élèves';
  R_ColTime          := 'Horaire';
  R_AbsDayTotal      := 'Total des cas enregistrés ce jour : ';
  R_JusCount         := 'Nombre d''enregistrements : ';
  R_JusProcessed     := 'Traitement effectué sur ';
  R_JusMedCert       := 'Certificat médical';
  R_JusConfirmUnjust := 'Voulez-vous annuler la justification des enregistrements sélectionnés ?';
  R_FromLbl          := 'Du ';
  R_ToLbl            := ' au ';
  R_UsrPassHint      := 'Laissez les deux champs vides pour conserver le mot de passe actuel.';
  R_UsrCreatedAt     := 'Date de création';
  R_UsrPassRequired  := 'Un mot de passe est obligatoire pour un nouvel utilisateur.';
  R_UsrLoginTaken    := 'Ce nom d''utilisateur est déjà utilisé.';
  R_UsrNoSelfDelete  := 'Vous ne pouvez pas supprimer votre propre compte en cours d''utilisation.';
  R_SetThrHint       := 'Nombre d''absences non justifiées à partir duquel le document est proposé.';
  R_SetThrOrder      := 'Les seuils doivent être croissants : seuil 1 < seuil 2 < seuil 3.';
  R_RepType          := 'Type d''état';
  R_RepRows          := 'Nb de lignes';
  R_RepPreview       := 'Aperçu';
  R_RepHintDaily     := 'Relevé de toutes les absences et retards enregistrés un jour donné.';
  R_RepHintReg       := 'Registre détaillé des absences et retards sur une période.';
  R_RepHintClass     := 'Synthèse du nombre d''absences et de retards par classe.';
  R_RepHintTop       := 'Classement des élèves selon le nombre d''absences.';
  R_RepHintRate      := 'Taux de présence = 100% moins (absences / (nb élèves × jours ouvrés × nb séances)).';
  R_ColTotal         := 'Total';
  R_ColJust          := 'Justifiées';
  R_ColUnjust        := 'Non justifiées';
  R_ColTotalAbs      := 'Total absences';
  R_RepPrintOnly     := 'Cet état est généré directement pour impression. Cliquez sur « Imprimer ».';
  R_RepRowCount      := 'Nombre de lignes : ';
  R_RepRateTitle     := 'Taux de présence et d''absence par classe';
  R_RepWorkDays      := '   -   Jours ouvrés : ';
  R_RepSlotsPerDay   := '   -   Séances par jour : ';
  R_ColNbStudents    := 'Nb élèves';
  R_ColPossible      := 'Séances possibles';
  R_ColAbsHours      := 'Heures d''absence';
  R_ColRateAbs       := 'Taux d''absence %';
  R_ColRatePres      := 'Taux de présence %';
  R_RepGlobalAbs     := 'Taux global d''absence de l''établissement : ';
  R_RepGlobalPres    := '   -   Taux global de présence : ';
  R_NotStudent       := 'Élève';
  R_NotSelectStudent := 'Veuillez sélectionner un élève.';
  R_NotSender        := 'Expéditeur';
  R_NotRecipient     := 'Destinataire';
  R_NotAddress       := 'Adresse';
  R_NotStudentName   := 'Nom et prénom de l''élève';
  R_PrmDefReason     := 'Retard à l''entrée';
  R_PrmDocTitle      := 'Billet d''entrée en classe';
  R_CrtDefPurpose    := 'pour servir et valoir ce que de droit';
  R_CrtDocTitle      := 'CERTIFICAT DE SCOLARITÉ';
  R_CrtNoPrefix      := 'N° : ';
  R_RepHdrRepublic   := 'République Algérienne Démocratique et Populaire';
  R_RepHdrMinistry   := 'Ministère de l''Éducation Nationale';
  R_SetMediaGroup   := 'Logo et photo de l''etablissement';
  R_SetLogo         := 'Logo';
  R_SetCover        := 'Photo de couverture';
  R_SetPickImg      := 'Choisir une image ...';
  R_SetClearImg     := 'Retirer';
  R_SetImgHint      := 'Formats acceptes : PNG, JPG, BMP. Copiee dans le dossier du programme.';
  R_CardSubStudents := 'Dossiers et inscriptions';
  R_CardSubAbsence  := 'Feuille de presence du jour';
  R_CardSubJustify  := 'Traiter les absences non justifiees';
  R_CardSubNotices  := 'Avis et convocations des tuteurs';
  R_CardSubDocs     := 'Billet d''entree et certificat';
  R_CardSubReports  := 'Syntheses et taux de presence';
  R_CardSubRefData  := 'Niveaux, matieres, seances';
  R_CardSubUsers    := 'Comptes et droits d''acces';
  R_CardSubSettings := 'Etablissement et seuils';
  R_MnuSampleData                  := 'Inserer des donnees de demonstration';
  R_SampleConfirm                  := 'Des donnees de demonstration completes seront inserees : 90 eleves' +
                                      ' (laureats du BEM 2026), enseignants, utilisateurs,' + #13#10 +
                                      'absences, retards, justifications, avis, billets et certificats.' +
                                      #13#10 + #13#10 +
                                      'Les tables deja remplies ne seront pas touchees. Continuer ?';
  R_SampleDone                     := 'Donnees de demonstration inserees :';
  R_SampleNone                     := 'Toutes les tables contiennent deja des donnees, rien ajoute.';
end;

{ ==========================================================================
  الواجهة البرمجية / API
  ========================================================================== }
procedure SetLanguage(ALang: TAppLang);
begin
  FLang := ALang;
  if ALang = langFR then
    LoadFrench
  else
    LoadArabic;
end;

procedure SetLanguageByCode(const ACode: string);
begin
  if SameText(Trim(ACode), 'FR') then
    SetLanguage(langFR)
  else
    SetLanguage(langAR);
end;

function CurrentLang: TAppLang;
begin
  Result := FLang;
end;

function LangCode: string;
begin
  if FLang = langFR then
    Result := 'FR'
  else
    Result := 'AR';
end;

function IsRTL: Boolean;
begin
  { العربية من اليمين إلى اليسار، الفرنسية من اليسار إلى اليمين }
  Result := FLang = langAR;
end;

function LangDisplayName(ALang: TAppLang): string;
begin
  if ALang = langFR then
    Result := R_LangFrench
  else
    Result := R_LangArabic;
end;

initialization
  { ضمان امتلاء النصوص قبل إنشاء أي نافذة }
  SetLanguage(langAR);

end.
