object frmLogin: TfrmLogin
  Left = 300
  Top = 200
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Login'
  ClientHeight = 300
  ClientWidth = 430
  Color = clBtnFace
  Font.Charset = ARABIC_CHARSET
  Font.Color = clWindowText
  Font.Height = -14
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 17
  object pnlTop: TPanel
    Left = 0
    Top = 0
    Width = 430
    Height = 95
    Align = alTop
    BevelOuter = bvNone
    Color = clHighlight
    ParentBackground = False
    TabOrder = 0
    object lblApp: TLabel
      Left = 0
      Top = 22
      Width = 430
      Height = 25
      Alignment = taCenter
      AutoSize = False
      Caption = 'App'
      Font.Charset = ARABIC_CHARSET
      Font.Color = clWhite
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object lblSchool: TLabel
      Left = 0
      Top = 55
      Width = 430
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Caption = 'School'
      Font.Charset = ARABIC_CHARSET
      Font.Color = clWhite
      Font.Height = -14
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlBody: TPanel
    Left = 0
    Top = 95
    Width = 430
    Height = 150
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object lblUser: TLabel
      Left = 250
      Top = 30
      Width = 150
      Height = 20
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'User'
    end
    object lblPass: TLabel
      Left = 250
      Top = 72
      Width = 150
      Height = 20
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Password'
    end
    object lblHint: TLabel
      Left = 20
      Top = 118
      Width = 380
      Height = 18
      Alignment = taCenter
      AutoSize = False
      Caption = 'hint'
      Font.Charset = ARABIC_CHARSET
      Font.Color = clGrayText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object edUser: TEdit
      Left = 30
      Top = 27
      Width = 205
      Height = 25
      TabOrder = 0
    end
    object edPass: TEdit
      Left = 30
      Top = 69
      Width = 205
      Height = 25
      PasswordChar = '*'
      TabOrder = 1
      OnKeyPress = edPassKeyPress
    end
  end
  object pnlBottom: TPanel
    Left = 0
    Top = 245
    Width = 430
    Height = 55
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 2
    object btnLogin: TButton
      Left = 230
      Top = 10
      Width = 105
      Height = 33
      Caption = 'Login'
      Default = True
      TabOrder = 0
      OnClick = btnLoginClick
    end
    object btnCancel: TButton
      Left = 105
      Top = 10
      Width = 105
      Height = 33
      Cancel = True
      Caption = 'Cancel'
      TabOrder = 1
      OnClick = btnCancelClick
    end
  end
end
